### ISSUE TITLE
Support for Xamarin

### ISSUE THREAD

**Issue by philipdw** [adamhathcock/sharpcompress#173]
Hi, 

I'm not sure this is an issue, but I can't see where to post any questions. Forgive me if this is the wrong place to write this and feel free to move this query or ask me to repost it elsewhere.

I have cloned sharpcompress (which looks excellent, by the way!) to git and have tried to open my local copy in Xamarin Studio on OSX. I don't seem to be able to do this because the solution contains xproj files and not csproj files.

I am not too familiar with xproj - from what I've read they seem a recent innovation in VS. I wonder if we can have a separate sln file linking to csproj equivalents so that this project is easier to build on the Mac using Xamarin. Ultimately I intend to use this on Mono.

Kind regards - and thanks for all the work, Adam.

Phil Whittington

**Comment by adamhathcock** [comment]
xproj is the new project system introduced by the .NET Core projects and being cross platform with .NET Standard.  csproj will be reintroduced but with a major refactor https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/

Did you try using NuGet as a library instead of needing the source?

xproj is only supported by VS2015 Update 3 with the .NET Core Preview 2 Tooling (get at http://dot.net) or with VS Code and the proper extensions.  JetBrains Rider also supports too.

**Comment by philipdw** [comment]
Hi Adam,

Thanks for your speedy response and apologies for my own slow reply. I think nuget may be the right solution for me right now. Or I may try re-creating the csproj files.

Thanks for all the work you've put in - it's an excellent project.

Phil
