### ISSUE TITLE
ArchiveEntry.Key is dependent on the archivetype

### ISSUE THREAD

**Issue by evpxregu** [adamhathcock/sharpcompress#201]
Hi,

When I run the following code the directory seperator in the IArchiveEntry.Key is different for different archive types.

```
var _archive = new ArchiveFactory.Open(file, options);
foreach (var entry in _archive.Entries)
{
    Console.WriteLine(entry.Key);
}

```

Output for a .rar file:

> subfolder\folder in subfolder\test fiel in sub-sub-subfolder.txt 
> subfolder\test fiel in sub-subfolder.txt 
> subfolder\folder in subfolder 

output for a .zip file

> subfolder/folder in subfolder/test fiel in sub-sub-subfolder.txt 
> subfolder/test fiel in sub-subfolder.txt 
> subfolder/folder in subfolder 0 

Is this by design or a bug? Both archives are created on the same computer.

**Comment by adamhathcock** [comment]
It seems likely there's a bug in creating where I hardcoded the path separator.  I'm not sure I should use he OS's separator or always pick one.

The archive specs may have one specifically.  I'll have to look it up.

**Comment by elgonzo** [comment]
Since SharpCompress is handling multiple different archive formats, it would make sense to normalize the path separator so that archive entry keys always appear in the same text format no matter which archive format is being read.

Personally, i would suggest to have a configuration parameter (i.e. a property in _ReaderOptions_) of type `char` which the developer/user can set to the separator as they prefer. The default value of this property should be the OS separator.

However, SharpCompress needs to pay attention when writing entries to an archive and if necessary convert whatever path separator chosen by the developer or SharpCompress to the path separator character as demanded by the particular archive format. For example, creating a TAR archive would require using '/' as separator char. The same is also true for the ZIP format (while many zip implementations on Windows do handle back-slashes in zip entry names, many zip implementation in Linux/MacOS/etc... do not).

**Comment by leezer3** [comment]
https://github.com/adamhathcock/sharpcompress/pull/114

You've got a hardcoded path separator issue in your RAR extractor
https://github.com/adamhathcock/sharpcompress/blob/master/src/SharpCompress/Common/Rar/Headers/FileHeader.cs#L168

Dumping the switch statement in favour of this ought to fix it:
```
if (Path.DirectorySeparatorChar == '/')
{
	return path.Replace('\\', '/');
}
else if (Path.DirectorySeparatorChar == '\\')
{
	return path.Replace('/', '\\');
}
```

RAR always wants a **\** as it's path separator.
Note:
Haven't tested this on create, hence why I'm not running up a pull request, but I don't see any reason for it to fail.

**Comment by adamhathcock** [comment]
I'll look into this soon.  I was thinking archive formats want something specific and SharpCompress will have to adjust it one top of the formats like you're saying.

**Comment by adamhathcock** [comment]
Finally made a PR for this https://github.com/adamhathcock/sharpcompress/pull/238
