### ISSUE TITLE
Can't get the root folder in some zip file.

### ISSUE THREAD

**Issue by kyuranger** [adamhathcock/sharpcompress#538]
Here is the sample of the zip file:
https://1drv.ms/u/s!AtcqjirAlaGYi4gSHBFiyRiNpU3sVg?e=d7NX60

And here is my code:
                       var archive = ZipArchive.Open(filename);                     
                        archive.Entries.ToList().ForEach(X =>
                        {
                            Debug.WriteLine(X.Key);
                        });

It will output all the file and folder except the root folder below:
k-sample-dl-h3101/

What's wrong with this? Is it a bug? Thank you.

**Comment by Deilan** [comment]
Having the same issue here

**Comment by kyuranger** [comment]
> Having the same issue here. Dupe of #267

It seems it is the same problem. But while it doesn't be fixed since 2017.

Now I have to check whether the root folder missing every time.

**Comment by kyuranger** [comment]
And also, I am not sure whether this problem only occurs in the root folder or may occur in any other folder.

**Comment by adamhathcock** [comment]
#267 does not have the "root" folder as a key in the archive.  SharpCompress won't add extra keys when reading or writing.  That's a higher level concern.

I haven't looked at your file but I imagine it's the same issue.  There just isn't the entry in the archive that you expect.

**Comment by Deilan** [comment]
Is there a proposed proper workaround for that?

**Comment by adamhathcock** [comment]
Workaround for what?  A key that isn't in the archive?  

I don't know what you're trying to do other than something you expect is missing.  Handle the missing key with your code.

If you're saying SharpCompress is making an archive without a key you expect then it's because the creating code wasn't told to make the key.  

There is no zip standard about how folder keys should be handled.  They're not even required.  I personally ignore them.

**Comment by kyuranger** [comment]
OK, thanks a lot.
